### ISSUE TITLE
Request PVELAD Dataset

### ISSUE THREAD

**Issue by pawara101** [binyisu/PVEL-AD#10]
Hi Iam  Pawara, a MSc student from Sri Lanka. I would greatly appreciate your providing the Photovoltaic Electroluminescence Anomaly Detection dataset (PVEL-AD) for my MSc research.
The request form is attached.

Appreciate your early action @binyisu 
Gsuit mail - pawara.23@cse.mrt.ac.lk

**Comment by KarmaQI** [comment]
May I ask if you have received a reply by now?

**Comment by pawara101** [comment]
Yeah i have recieved

**Comment by Bin-ze** [comment]
> Yeah i have recieved

Hello, can you share the dataset with me? I am an algorithm engineer working on photovoltaic panel defect detection. I would be grateful if you can share the dataset with me.

**Comment by pawara101** [comment]
Sorry, I can't do that. Those data have their authorship. Please contact one of the authors.
